server:
  port: 9296

spring:
   application:
      name: CONFIG-SERVER
   boot:
    admin:
      client:
        url: http://localhost:8081   
   cloud:
    config:
      server:
        git:
          uri: https://github.com/lovachittumuri/config-server
          clone-on-start: true