server:
  port: 9191
#========= Application Name and its Routing =====  

spring:
   application:
      name: API-GATEWAY
   boot:
    admin:
      client:
        url: http://localhost:8081
   cloud:
     gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
          - Path=/department/**
#========= API- GATEWAY Service Registry =====  

