server:
  port: 9191
#========= Application Name and its Routing =====  

spring:
   application:
      name: API-GATEWAY
   cloud:
     gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
          - Path=/department/**
#========= API- GATEWAY Service Registry =====  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
