management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
server:
  port: 9001

spring:
  application:
      name: DEPARTMENT-SERVICE
      zipkin: 
        base-url:http://127.0.0.1:9411/
  boot:    
    admin:
      client:
        url: http://localhost:8081
    